# Site settings
title: Taufiq's Blog
description: A personal blog about development and life
baseurl: "" # Leave empty if your site is at username.github.io
url: "https://taufiq-ai.github.io" # Replace with your GitHub Pages URL

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Blog settings
permalink: /blog/:title/
paginate: 10
paginate_path: "/blog/page:num/"

# Author info
author:
  name: Taufiq
  email: taufiqkhantusar@gmail.com

# Social links (optional)
github_username: taufiq-ai
linkedin_username: taufiq-khan-tusar

# Exclude files from build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md